//! Self-contained HTML report renderer.
//!
//! Produces a single `.html` file with the embedded CSS, JS, and inline
//! SVG vendor logos. Opens in any browser; no external assets except the
//! Inter / JetBrains Mono fonts pulled from Google Fonts CDN at view time.

// We deliberately use `write!(s, "…\n")` (rather than `writeln!`) so the
// HTML template reads top-to-bottom in source order — every line in the
// rendered output corresponds to exactly one `write!` call.
#![allow(clippy::write_with_newline)]

use std::fmt::Write as _;
use std::path::Path;

use paysight_core::{
    AntibotHit, AntibotKind, AuthGateStatus, Confidence, PaymentCategory, PaymentHit, ScanReport,
};

use crate::assets::{payment_logo, protection_logo, PLACEHOLDER_SVG, SCRIPT, STYLESHEET};
use crate::ReportError;

const SCORE_REFERENCE_MAX: u32 = 40;

pub fn render_html<P: AsRef<Path>>(reports: &[ScanReport], out: P) -> Result<(), ReportError> {
    let html = render_html_string(reports);
    std::fs::write(out, html)?;
    Ok(())
}

pub fn render_html_string(reports: &[ScanReport]) -> String {
    let mut s = String::with_capacity(64 * 1024);
    let now_human = current_timestamp_human();

    write!(
        s,
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n\
<meta charset=\"utf-8\"/>\n\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n\
<title>PaySight scan report — {} target{}</title>\n\
<style>\n{}\n</style>\n\
</head>\n<body>\n<main>\n",
        reports.len(),
        if reports.len() == 1 { "" } else { "s" },
        STYLESHEET
    )
    .unwrap();

    // Header
    let _ = write!(
        s,
        "<header class=\"header\">\n  <div class=\"brand\">\n    <div class=\"wordmark\">PaySight</div>\n    <div class=\"tagline\">Payment + protection stack reconnaissance</div>\n  </div>\n  <div class=\"meta\"><strong>{} target{}</strong>generated {}</div>\n</header>\n<hr class=\"divider\"/>\n",
        reports.len(),
        if reports.len() == 1 { "" } else { "s" },
        escape_html(&now_human),
    );

    // Cards
    for report in reports {
        render_card(&mut s, report);
    }

    let _ = write!(
        s,
        "<footer>Generated by <a href=\"https://github.com/captainyugi00/PaySight\">PaySight</a> · {} · scans run with browser-grade TLS fingerprinting via wreq</footer>\n</main>\n<script>\n{}\n</script>\n</body>\n</html>\n",
        escape_html(&now_human),
        SCRIPT
    );
    s
}

fn render_card(s: &mut String, report: &ScanReport) {
    let _ = write!(s, "<section class=\"card\">\n");

    // Head
    let _ = write!(
        s,
        "<div class=\"card-head\">\n  <div>\n    <h2 class=\"target\">{}</h2>\n    <span class=\"final-url\">→ {}</span>\n    <div class=\"meta-row\">\n      <span class=\"chip\"><span class=\"chip-num\">{}</span>&nbsp;probes</span>\n      <span class=\"chip\"><span class=\"chip-num\">{}</span>&nbsp;ms</span>\n      {}\n    </div>\n  </div>\n",
        escape_html(&report.target),
        escape_html(&report.final_url),
        report.probes.len(),
        report.elapsed_ms,
        gate_pill(report.auth_gate),
    );
    let _ = write!(s, "</div>\n");

    // Primary gateway callout
    if let Some(top) = report.primary_gateway() {
        let _ = write!(
            s,
            "<div class=\"primary\">\n  <div class=\"primary-logo\">{}</div>\n  <div class=\"primary-meta\">\n    <div class=\"primary-tag\">Primary gateway</div>\n    <div class=\"primary-vendor\">{}</div>\n    <div class=\"primary-sub\">{} · score {}</div>\n  </div>\n</div>\n",
            inline_svg(payment_logo(&top.slug)),
            escape_html(&top.vendor),
            escape_html(top.confidence.label()),
            top.score,
        );
    }

    // Payment table
    let _ = write!(
        s,
        "<div class=\"section\">\n  <h3 class=\"section-title\">Payment stack</h3>\n"
    );
    if report.payment_hits.is_empty() {
        let _ = write!(s, "  <div class=\"empty\">No payment-vendor signatures matched. The target's checkout SDK is likely loaded only after authentication or with cart items.</div>\n");
    } else {
        let mut hits = report.payment_hits.clone();
        hits.sort_by(|a, b| {
            a.category
                .label()
                .cmp(b.category.label())
                .then(b.score.cmp(&a.score))
        });
        render_payment_table(s, &hits);
    }
    let _ = write!(s, "</div>\n");

    // Antibot table
    let _ = write!(
        s,
        "<div class=\"section\">\n  <h3 class=\"section-title\">Bot mitigation / WAF / CDN</h3>\n"
    );
    if report.antibot_hits.is_empty() {
        let _ = write!(
            s,
            "  <div class=\"empty\">No protection-vendor signatures matched.</div>\n"
        );
    } else {
        render_antibot_table(s, &report.antibot_hits);
    }
    let _ = write!(s, "</div>\n");

    // Cookies
    if !report.cookies.is_empty() {
        let _ = write!(
            s,
            "<div class=\"section\">\n  <h3 class=\"section-title\">Cookies set during probes</h3>\n  <div class=\"cookies\">\n"
        );
        for c in &report.cookies {
            let _ = write!(
                s,
                "    <span class=\"cookie-tag\">{}</span>\n",
                escape_html(&c.name)
            );
        }
        let _ = write!(s, "  </div>\n</div>\n");
    }

    let _ = write!(s, "</section>\n");
}

fn render_payment_table(s: &mut String, hits: &[PaymentHit]) {
    let _ = write!(
        s,
        "  <table class=\"tbl\">\n    <thead><tr><th></th><th>Category</th><th>Vendor</th><th>Score</th><th>Confidence</th><th>Patterns</th></tr></thead>\n    <tbody>\n"
    );
    for hit in hits {
        let pct = score_to_pct(hit.score);
        let _ = write!(
            s,
            "      <tr>\n        <td class=\"logo-cell\"><span class=\"logo\">{}</span></td>\n        <td><span class=\"cat {}\">{}</span></td>\n        <td class=\"vendor\">{}</td>\n        <td><div class=\"score-bar\"><div class=\"score-track\"><div class=\"score-fill\" data-pct=\"{}\"></div></div><span class=\"score-num\">{}</span></div></td>\n        <td><span class=\"conf {}\">{}</span></td>\n        <td class=\"patterns\">{}</td>\n      </tr>\n",
            inline_svg(payment_logo(&hit.slug)),
            payment_cat_class(hit.category),
            escape_html(hit.category.label()),
            escape_html(&hit.vendor),
            pct,
            hit.score,
            confidence_class(hit.confidence),
            escape_html(hit.confidence.label()),
            escape_html(&truncate(&hit.matched_patterns.join(", "), 100)),
        );
    }
    let _ = write!(s, "    </tbody>\n  </table>\n");
}

fn render_antibot_table(s: &mut String, hits: &[AntibotHit]) {
    let _ = write!(
        s,
        "  <table class=\"tbl\">\n    <thead><tr><th></th><th>Kind</th><th>Vendor</th><th>Score</th><th>Confidence</th><th>Patterns</th></tr></thead>\n    <tbody>\n"
    );
    for hit in hits {
        let pct = score_to_pct(hit.score);
        let _ = write!(
            s,
            "      <tr>\n        <td class=\"logo-cell\"><span class=\"logo\">{}</span></td>\n        <td><span class=\"cat {}\">{}</span></td>\n        <td class=\"vendor\">{}</td>\n        <td><div class=\"score-bar\"><div class=\"score-track\"><div class=\"score-fill\" data-pct=\"{}\"></div></div><span class=\"score-num\">{}</span></div></td>\n        <td><span class=\"conf {}\">{}</span></td>\n        <td class=\"patterns\">{}</td>\n      </tr>\n",
            inline_svg(protection_logo(&hit.slug)),
            antibot_class(hit.kind),
            escape_html(hit.kind.label()),
            escape_html(&hit.vendor),
            pct,
            hit.score,
            confidence_class(hit.confidence),
            escape_html(hit.confidence.label()),
            escape_html(&truncate(&hit.matched_patterns.join(", "), 100)),
        );
    }
    let _ = write!(s, "    </tbody>\n  </table>\n");
}

fn gate_pill(g: AuthGateStatus) -> String {
    match g {
        AuthGateStatus::Open => "<span class=\"gate open\">checkout open</span>".into(),
        AuthGateStatus::Gated => "<span class=\"gate gated\">auth-gated</span>".into(),
        AuthGateStatus::Unknown => "<span class=\"gate unknown\">gate unknown</span>".into(),
    }
}

fn payment_cat_class(c: PaymentCategory) -> &'static str {
    match c {
        PaymentCategory::PrimaryGateway => "primary_gateway",
        PaymentCategory::Wallet => "wallet",
        PaymentCategory::BuyNowPayLater => "bnpl",
        PaymentCategory::BankRedirect => "bank_redirect",
        PaymentCategory::ThreeDSecure => "three_d_secure",
        PaymentCategory::SiteBuilder => "site_builder",
    }
}

fn antibot_class(k: AntibotKind) -> &'static str {
    match k {
        AntibotKind::Cdn => "cdn",
        AntibotKind::Waf => "waf",
        AntibotKind::BotManager => "bot_manager",
        AntibotKind::Captcha => "captcha",
        AntibotKind::Fingerprint => "fingerprint",
    }
}

fn confidence_class(c: Confidence) -> &'static str {
    match c {
        Confidence::None | Confidence::Weak => "weak",
        Confidence::Moderate => "moderate",
        Confidence::Strong => "strong",
        Confidence::VeryStrong => "very_strong",
    }
}

fn score_to_pct(score: u32) -> u32 {
    let pct = (score as f32 / SCORE_REFERENCE_MAX as f32) * 100.0;
    pct.round().clamp(0.0, 100.0) as u32
}

/// Strip the XML prologue so the SVG can be embedded directly inside a
/// span / div.
fn inline_svg(bytes: Option<&[u8]>) -> String {
    let raw = bytes.unwrap_or(PLACEHOLDER_SVG);
    let s = std::str::from_utf8(raw).unwrap_or("");
    if let Some(idx) = s.find("<svg") {
        s[idx..].to_string()
    } else {
        s.to_string()
    }
}

fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        let mut out: String = s.chars().take(max - 1).collect();
        out.push('…');
        out
    }
}

fn current_timestamp_human() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let (y, mo, d, h, mi, se) = epoch_to_ymdhms(secs);
    format!("{y:04}-{mo:02}-{d:02} {h:02}:{mi:02}:{se:02} UTC")
}

fn epoch_to_ymdhms(secs: u64) -> (i32, u32, u32, u32, u32, u32) {
    let days = secs / 86_400;
    let rem = secs % 86_400;
    let h = (rem / 3600) as u32;
    let mi = ((rem % 3600) / 60) as u32;
    let se = (rem % 60) as u32;
    let z = days as i64 + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    let y = if mo <= 2 { y + 1 } else { y };
    (y as i32, mo, d, h, mi, se)
}
